//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herschel.Loader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Herschel.Loader.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC [load].[CleanUp]
        ///GO
        ///.
        /// </summary>
        internal static string CleanupPointing {
            get {
                return ResourceManager.GetString("CleanupPointing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULK INSERT [load].[RawObservation]
        ///FROM &apos;[$datafile]&apos;
        ///WITH 
        ///( 
        ///   DATAFILETYPE = &apos;char&apos;,
        ///   FIELDTERMINATOR = &apos;|&apos;,
        ///   ROWTERMINATOR = &apos;\n&apos;,
        ///   TABLOCK
        ///).
        /// </summary>
        internal static string LoadObservation {
            get {
                return ResourceManager.GetString("LoadObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BULK INSERT [load].[RawPointing]
        ///FROM &apos;[$datafile]&apos;
        ///WITH 
        ///( 
        ///   DATAFILETYPE = &apos;char&apos;,
        ///   FIELDTERMINATOR = &apos; &apos;,
        ///   ROWTERMINATOR = &apos;\n&apos;,
        ///   TABLOCK
        ///).
        /// </summary>
        internal static string LoadPointing {
            get {
                return ResourceManager.GetString("LoadPointing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC load.MergeObservations
        ///GO
        ///
        ///EXEC load.MergeScanMaps
        ///GO
        ///
        ///EXEC load.MergeRasterMaps
        ///GO
        ///
        ///EXEC load.MergeSpectro
        ///GO.
        /// </summary>
        internal static string MergeObservation {
            get {
                return ResourceManager.GetString("MergeObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC [load].[MergePointing]
        ///GO
        ///
        ///EXEC [load].[DetectObservations]
        ///GO
        ///
        ///EXEC [load].[DetectLegs]
        ///GO
        ///
        ///EXEC [load].[GenerateFootprint]
        ///GO
        ///
        ///EXEC [load].[GeneratePacsSpireParallel]
        ///GO
        ///
        ///EXEC [load].[GenerateHtm]
        ///GO
        ///.
        /// </summary>
        internal static string MergePointing {
            get {
                return ResourceManager.GetString("MergePointing", resourceCulture);
            }
        }
    }
}
