USE [master]
GO

/****** Object:  Database [Herschel]    Script Date: 2014.03.07. 11:45:11 ******/
CREATE DATABASE Herschel
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Herschel_0', FILENAME = N'C:\Data\Raid6_0\vo\sql_db\Herschel\Herschel_0.mdf' , SIZE = 250MB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
( NAME = N'Herschel_1', FILENAME = N'C:\Data\Raid6_1\vo\sql_db\Herschel\Herschel_1.ndf' , SIZE = 250MB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'Herschel_0_log', FILENAME = N'C:\Data\Raid6_0\vo\sql_db\Herschel\Herschel_0_log.ldf' , SIZE = 25MB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'Herschel_1_log', FILENAME = N'C:\Data\Raid6_1\vo\sql_db\Herschel\Herschel_1_log.ldf' , SIZE = 25MB , MAXSIZE = 2048GB , FILEGROWTH = 0)
GO

ALTER DATABASE [Herschel] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Herschel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Herschel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Herschel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Herschel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Herschel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Herschel] SET ARITHABORT OFF 
GO

ALTER DATABASE [Herschel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Herschel] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Herschel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Herschel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Herschel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Herschel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Herschel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Herschel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Herschel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Herschel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Herschel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Herschel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Herschel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Herschel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Herschel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Herschel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Herschel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Herschel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Herschel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Herschel] SET  MULTI_USER 
GO

ALTER DATABASE [Herschel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Herschel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Herschel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Herschel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Herschel] SET  READ_WRITE 
GO


